#!/bin/bash
cd "$(dirname "$0")/.."
source ./script/setup.sh

zip_uri='' # mandatory
cask_name='' # mandatory
build_version="0.0.0-SNAPSHOT"
while test $# -gt 0; do
    case $1 in
        --build-version) build_version="$2"; shift 2;;
        --zip-uri) zip_uri="$2"; shift 2;;
        --cask-name) cask_name="$2"; shift 2;;
        *) echo "Unknown arg $1"; exit 1;;
    esac
done

if test -z "$zip_uri"; then echo "--zip-uri is mandatory" > /dev/stderr; exit 1; fi
if test -z "$cask_name"; then echo "--cask-name is mandatory" > /dev/stderr; exit 1; fi

case "$cask_name" in
    aerospace-edge|aerospace-edge-dev) ;;
    *) echo "Unknown cask name: $cask_name. Allowed cask names: aerospace-edge, aerospace-edge-dev" > /dev/stderr; exit 1;;
esac
# No conflicts_with between the two casks: 'aerospace-edge' lives in the vitorebatista/tap tap and
# 'aerospace-edge-dev' is only ever installed from a local .rb, so each would name a cask Homebrew
# can't resolve on the other's install. install-from-sources.sh already uninstalls the dev cask first.

zip_file=''
if test -f "$zip_uri"; then
    zip_file=$zip_uri
    zip_uri="file://$(realpath "$zip_file")"
elif grep -q '^http' <<< "$zip_uri"; then
    zip_file=/tmp/AeroSpace-edge-tmp.zip
    rm -rf $zip_file
    curl -L "$zip_uri" -o $zip_file
else
    echo "$zip_uri doesn't exist" > /dev/stderr; exit 1
fi
sha=$(shasum -a 256 "$zip_file" | awk '{print $1}')

cask_version=':latest' # Prevent 'Not upgrading aerospace-edge, the latest version is already installed'
zip_root_dir="AeroSpace-edge-v$build_version"
if ! grep -q SNAPSHOT <<< "$build_version"; then
    cask_version="'$build_version'"
    zip_root_dir=$(sed "s/$build_version/#{version}/g" <<< "$zip_root_dir")
    zip_uri=$(sed "s/$build_version/#{version}/g" <<< "$zip_uri")
fi

# The fork's lean release zip ships only the app + CLI (see dev-docs/fork-maintenance.md), while a full
# build-release.sh zip also carries shell completions and man pages. Emit only what's in the zip —
# a 'binary' stanza pointing at a missing path fails the install.
extra_stanzas=''
if unzip -l "$zip_file" | grep -q 'shell-completion/'; then
    extra_stanzas="
  binary \"$zip_root_dir/shell-completion/zsh/_aerospace-edge\",
      target: \"#{HOMEBREW_PREFIX}/share/zsh/site-functions/_aerospace-edge\"
  binary \"$zip_root_dir/shell-completion/bash/aerospace-edge\",
      target: \"#{HOMEBREW_PREFIX}/etc/bash_completion.d/aerospace-edge\"
  binary \"$zip_root_dir/shell-completion/fish/aerospace-edge.fish\",
      target: \"#{HOMEBREW_PREFIX}/share/fish/vendor_completions.d/aerospace-edge.fish\"
"
fi
if unzip -l "$zip_file" | grep -q 'manpage/'; then
    extra_stanzas="$extra_stanzas
  Dir[\"#{staged_path}/$zip_root_dir/manpage/*\"].each { |man| manpage man }
"
fi

rm -f ".release/$cask_name.rb" || true
mkdir -p .release
cat > ".release/$cask_name.rb" <<EOF
cask "$cask_name" do # THE FILE IS GENERATED BY build-brew-cask.sh
  version $cask_version
  sha256 "$sha"

  url "$zip_uri"
  name "AeroSpace-edge"
  desc "AeroSpace-edge is an i3-like tiling window manager for macOS"
  homepage "https://github.com/vitorebatista/AeroSpace-edge"

  depends_on macos: :ventura # macOS 13 (bare symbol means ">=")

  postflight do
    system "xattr -d com.apple.quarantine #{staged_path}/$zip_root_dir/bin/aerospace-edge"
    system "xattr -d com.apple.quarantine #{appdir}/AeroSpace-edge.app"
  end

  app "$zip_root_dir/AeroSpace-edge.app"
  binary "$zip_root_dir/bin/aerospace-edge"
$extra_stanzas
  caveats <<~CAVEATS
    Builds are signed ad-hoc, so macOS revokes the Accessibility grant on every install and
    upgrade. Enable AeroSpace-edge in System Settings > Privacy & Security > Accessibility,
    then launch it again.

    Do not mix update channels: if you upgrade via "Check for Updates..." in the menu bar,
    Homebrew's idea of the installed version goes stale. Use one or the other.
  CAVEATS
end
EOF
